# Generated by Django 4.1.1 on 2022-11-01 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('H_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('H_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=50, unique=True)),
                ('room_no', models.IntegerField()),
                ('room_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('H_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='home.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_id', models.CharField(max_length=50, unique=True)),
                ('H_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteli', to='home.hotel')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useri', to='home.user')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='home.rooms')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomn', to='home.rooms')),
            ],
        ),
    ]
