# Generated by Django 4.1.1 on 2022-11-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hotel_rooms_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='H_id',
            new_name='H',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='H_id',
            new_name='H',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='Userid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
